.\" Hey, EMACS: -*- nroff -*-
.TH KYLIN-ASSISTANT-BACKEND 1 "22 DEC 2017"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
kylin-assistant-backend \- launch backends
.SH SYNOPSIS
.B kylin-assistant-backend
.SH DESCRIPTION
.B kylin-assistant-backend
It is used to launch backends.
.PP
.SH SEE ALSO
.BR kylin-assistant-backend (1),
.br
.SH AUTHOR
kylin-assistant-backend was written by lixiang <lixiang@kylinos.cn>.
.PP
This manual page was written by lixiang <lixiang@kylinos.cn>.

