.\" Hey, EMACS: -*- nroff -*-
.TH KYLIN-ASSISTANT-SESSION 1 "22 DEC 2017"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
kylin-assistant-session \- launch backends
.SH SYNOPSIS
.B kylin-assistant-session
.SH DESCRIPTION
.B kylin-assistant-session
It is used to launch backends.
.PP
.SH SEE ALSO
.BR kylin-assistant-session (1),
.br
.SH AUTHOR
kylin-assistant-session was written by lixiang <lixiang@kylinos.cn>.
.PP
This manual page was written by lixiang <lixiang@kylinos.cn>.

