.\" Hey, EMACS: -*- nroff -*-
.TH KYLIN-ASSISTANT-SYSTEM 1 "22 DEC 2017"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
kylin-assistant-system \- launch backends
.SH SYNOPSIS
.B kylin-assistant-system
.SH DESCRIPTION
.B kylin-assistant-system
It is used to launch backends. Need to use root privilige.
.PP
.SH SEE ALSO
.BR kylin-assistant-system (1),
.br
.SH AUTHOR
kylin-assistant-system was written by lixiang <lixiang@kylinos.cn>.
.PP
This manual page was written by lixiang <lixiang@kylinos.cn>.

