.\" Hey, EMACS: -*- nroff -*-
.TH KYLIN-ASSISTANT-SYSTEMDAEMON 1 "03 AUG 2021"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
kylin-assistant-systemdaemon \- launch systemdaemon
.SH SYNOPSIS
.B kylin-assistant-systemdaemon
.SH DESCRIPTION
.B kylin-assistant-systemdaemon
It is used to launch systemdaemon.
.PP
.SH SEE ALSO
.BR kylin-assistant-systemdaemon (1),
.br
.SH AUTHOR
kylin-assistant-systemdaemon was written by Yang Min <yangmin@kylinos.cn>.
.PP
This manual page was written by Yang Min <yangmin@kylinos.cn>.
