.\" Hey, EMACS: -*- nroff -*-
.TH KYLIN-ASSISTANT 1 "22 DEC 2017"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
kylin-assistant \- launch kylin-assistant frontends
.SH SYNOPSIS
.B kylin-assistant
.SH DESCRIPTION
.B kylin-assistant
It is used to launch frontends.
.PP
.SH SEE ALSO
.BR kylin-assistant (1),
.br
.SH AUTHOR
kylin-assistant was written by lixiang <lixiang@kylinos.cn>.
.PP
This manual page was written by lixiang <lixiang@kylinos.cn>.

