.\" Hey, EMACS: -*- nroff -*-
.TH YOUKER-SYSTEM 1 "19 AUG 2013"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
youker-sudo \- launch backends
.SH SYNOPSIS
.B youker-sudo
.SH DESCRIPTION
.B youker-sudo
It is used to launch backends. Need to use root privilige.
.PP
.SH SEE ALSO
.BR youker-sudo (1),
.br
.SH AUTHOR
youker-sudo was written by Kobe <kobe24_lixiang@126.com>.
.PP
This manual page was written by shijing <jingshi@ubuntukylin.com>.

