.\" Hey, EMACS: -*- nroff -*-
.TH YOUKER-ASSISTANT 1 "19 AUG 2013"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
youker-assistant \- launch youker-assistant frontends
.SH SYNOPSIS
.B youker-assistant
.SH DESCRIPTION
.B youker-assistant
It is used to launch frontends.
.PP
.SH SEE ALSO
.BR youker-assistant (1),
.br
.SH AUTHOR
youker-assistant was written by Kobe <kobe24_lixiang@126.com>.
.PP
This manual page was written by shijing <jingshi@ubuntukylin.com>.

