.\" Hey, EMACS: -*- nroff -*-
.TH YOUKER-SESSION 1 "19 AUG 2013"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
youker-session \- launch backends
.SH SYNOPSIS
.B youker-session
.SH DESCRIPTION
.B youker-session
It is used to launch backends.
.PP
.SH SEE ALSO
.BR youker-session (1),
.br
.SH AUTHOR
youker-session was written by Kobe <kobe24_lixiang@126.com>.
.PP
This manual page was written by shijing <jingshi@ubuntukylin.com>.

