/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.kylin.assistant.qsessiondbus.xml -a sessionadaptor -c SessionAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "sessionadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SessionAdaptor
 */

SessionAdaptor::SessionAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SessionAdaptor::~SessionAdaptor()
{
    // destructor
}

QString SessionAdaptor::demoInfo()
{
    // handle method call com.kylin.assistant.qsessiondbus.demoInfo
    QString out0;
    QMetaObject::invokeMethod(parent(), "demoInfo", Q_RETURN_ARG(QString, out0));
    return out0;
}

void SessionAdaptor::exitService()
{
    // handle method call com.kylin.assistant.qsessiondbus.exitService
    QMetaObject::invokeMethod(parent(), "exitService");
}

