/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp shredInterfaceServer.xml -a ShredAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ShredAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class UkshredAdaptor
 */

UkshredAdaptor::UkshredAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

UkshredAdaptor::~UkshredAdaptor()
{
    // destructor
}

void UkshredAdaptor::exitDbus(const QString &data)
{
    // handle method call org.freedesktop.ukshred.exitDbus
    QMetaObject::invokeMethod(parent(), "exitDbus", Q_ARG(QString, data));
}

int UkshredAdaptor::shredFile(const QString &data)
{
    // handle method call org.freedesktop.ukshred.shredFile
    int response;
    QMetaObject::invokeMethod(parent(), "shredFile", Q_RETURN_ARG(int, response), Q_ARG(QString, data));
    return response;
}

