/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp shredInterfaceServer.xml -a ShredAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SHREDADAPTOR_H_1411959106
#define SHREDADAPTOR_H_1411959106

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.ukshred
 */
class UkshredAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.ukshred")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.ukshred\">\n"
"    <method name=\"shredFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"data\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"response\"/>\n"
"    </method>\n"
"    <method name=\"exitDbus\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"data\"/>\n"
"    </method>\n"
"    <signal name=\"responseFromServer\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"data\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    UkshredAdaptor(QObject *parent);
    virtual ~UkshredAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void exitDbus(const QString &data);
    int shredFile(const QString &data);
Q_SIGNALS: // SIGNALS
    void responseFromServer(const QString &data);
};

#endif
