name: youker-assistant
version: '2.4.2'
summary: Integrated tool to aid in routine system maintenance tasks
description: |
  Youker Assistant is a tool designed to help Ubuntu and Ubuntu Kylin 
  desktop users manage and maintain many aspects of their working 
  environment conveniently in a single application, providing a consistent
  user experience.
  
  Features currently included:
   * Detecting and displaying general system information
   * Unity and Mate user interface customization
   * System garbage cleaning

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  youker-assistant:
    command: desktop-launch youker-assistant
    desktop: usr/share/applications/youker-assistant.desktop
    plugs: [home, unity7, desktop, desktop-legacy]

parts:
  youker-assistant:
    plugin: qmake
    qt-version: qt4
    source: .
    build-packages: [g++, libqt4-dev, libglib2.0-dev]
    after: [desktop-qt4]
